import type { DesktopConfig } from './config.svelte';

/**
 * Looks: whole appearances, one click each - the equivalent of switching a
 * desktop's global theme, or of dropping someone's dotfiles into place.
 *
 * ## Why a look writes settings rather than being one
 *
 * The obvious design is a `look` setting that the stylesheets branch on. It
 * makes every other appearance setting a liar: choose Terminal, then set a
 * corner radius, and either the look ignores the slider or the slider silently
 * edits something the look then overrides. So a look is not a mode. It is a
 * set of values for the ordinary settings, written through the ordinary store,
 * after which every slider is still exactly what it says - and a look someone
 * has tuned is simply their own appearance, which is what a rice is.
 *
 * Each look is written as a *difference from the defaults* and applied as a
 * whole: a key it does not mention goes back to its default, so moving from
 * Retro to Glass leaves no bevel behind. A few settings are left out on
 * purpose - text size, whether anything animates and how fast - because those
 * are about the person using the desktop, not about how it is dressed.
 */

/** Every setting a look determines, in the order the Appearance dialog lists them. */
export const APPEARANCE_KEYS = [
  'fontFamily',
  'displayFont',
  'monoFont',
  'fontWeight',
  'displayWeight',
  'letterSpacing',
  'textShadow',
  'titleStyle',
  'titleDecor',
  'titleAlign',
  'titleWeight',
  'followTheme',
  'colorScheme',
  'schemeGround',
  'schemeInk',
  'schemeAccent',
  'surfaceHue',
  'surfaceChroma',
  'accentColor',
  'accentColor2',
  'panelOpacity',
  'panelBlur',
  'backdropSaturation',
  'panelBorder',
  'panelBorderWidth',
  'panelBorderStyle',
  'panelBorderColor',
  'borderAnimation',
  'panelShadow',
  'panelFill',
  'panelTexture',
  'cornerRadius',
  'panelPadding',
  'panelGlow',
  'density',
  'controlShape',
  'iconRadius',
  'iconLabelStyle',
  'barThickness',
  'barStyle',
  'scrollbars',
  'entranceStyle',
] as const satisfies readonly (keyof DesktopConfig)[];

/** Carried by an exported appearance as well, though no look sets them. */
export const SHARED_EXTRA_KEYS = [
  'fontSize',
  'animations',
  'motionScale',
  'staggerScale',
  'customCss',
] as const satisfies readonly (keyof DesktopConfig)[];

export type AppearanceKey = (typeof APPEARANCE_KEYS)[number];
export type Appearance = Pick<DesktopConfig, AppearanceKey>;
type ShareKey = AppearanceKey | (typeof SHARED_EXTRA_KEYS)[number];

export interface Look {
  id: string;
  label: string;
  description: string;
  /** Only what differs from the defaults. */
  values: Partial<Appearance>;
}

export const LOOKS: readonly Look[] = [
  {
    id: 'glass',
    label: 'Glass',
    description: 'The shipped look: frosted panels that take their colour from the Seelen theme.',
    values: {},
  },
  {
    id: 'hyprland',
    label: 'Hyprland',
    description: 'Catppuccin Mocha glass with a slowly turning gradient border and a deep drop shadow.',
    values: {
      colorScheme: 'catppuccin-mocha',
      panelOpacity: 55,
      panelBlur: 26,
      backdropSaturation: 140,
      panelBorder: 90,
      panelBorderWidth: 2,
      panelBorderColor: 'gradient',
      borderAnimation: true,
      panelShadow: 'deep',
      cornerRadius: 10,
      titleStyle: 'plain',
      entranceStyle: 'zoom',
    },
  },
  {
    id: 'terminal',
    label: 'Terminal',
    description: 'A tiling-WM status bar: Tokyo Night, monospace, square corners and bracketed titles.',
    values: {
      colorScheme: 'tokyo-night',
      fontFamily: 'Consolas',
      displayFont: 'Consolas',
      monoFont: 'Consolas',
      displayWeight: 400,
      titleStyle: 'lower',
      titleDecor: 'bracket',
      titleWeight: 700,
      panelOpacity: 92,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 45,
      panelBorderColor: 'ink',
      panelShadow: 'none',
      cornerRadius: 0,
      panelGlow: false,
      density: 'compact',
      controlShape: 'square',
      iconRadius: 0,
      iconLabelStyle: 'plain',
      barThickness: 8,
      barStyle: 'striped',
      scrollbars: 'hidden',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'nord',
    label: 'Nord Minimal',
    description: 'Opaque Nord cards with no edge and no shadow, and plenty of room inside.',
    values: {
      colorScheme: 'nord',
      displayWeight: 300,
      titleStyle: 'plain',
      titleWeight: 500,
      panelOpacity: 90,
      panelBlur: 0,
      panelTexture: false,
      panelBorderWidth: 0,
      panelShadow: 'none',
      cornerRadius: 8,
      panelPadding: 16,
      panelGlow: false,
      density: 'roomy',
      controlShape: 'subtle',
      barThickness: 3,
      entranceStyle: 'fade',
    },
  },
  {
    id: 'retro',
    label: 'Retro',
    description: 'Bevelled Motif-era frames with filled title bars, in Gruvbox.',
    values: {
      colorScheme: 'gruvbox-dark',
      fontFamily: 'Tahoma',
      displayFont: 'Tahoma',
      displayWeight: 400,
      titleStyle: 'plain',
      titleDecor: 'bar',
      titleWeight: 700,
      panelOpacity: 100,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 100,
      panelBorderWidth: 3,
      panelBorderStyle: 'outset',
      panelShadow: 'hard',
      cornerRadius: 0,
      panelPadding: 10,
      panelGlow: false,
      controlShape: 'square',
      iconRadius: 0,
      iconLabelStyle: 'pill',
      barThickness: 10,
      barStyle: 'striped',
      entranceStyle: 'drop',
    },
  },
  {
    id: 'brutal',
    label: 'Neo Brutal',
    description: 'Cream cards, thick black outlines, hard offset shadows and loud accents.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#fff8e7',
      schemeInk: '#161616',
      accentColor: '#ff5c8a',
      accentColor2: '#ffd23f',
      displayWeight: 800,
      titleDecor: 'underline',
      titleWeight: 800,
      panelOpacity: 100,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 100,
      panelBorderWidth: 3,
      panelBorderColor: 'ink',
      panelShadow: 'hard',
      cornerRadius: 6,
      panelGlow: false,
      controlShape: 'subtle',
      iconLabelStyle: 'pill',
      barThickness: 10,
      entranceStyle: 'drop',
    },
  },
  {
    id: 'synthwave',
    label: 'Synthwave',
    description: 'Neon edges that glow in the accent, over a purple wash.',
    values: {
      colorScheme: 'synthwave',
      textShadow: true,
      titleDecor: 'dot',
      panelOpacity: 72,
      panelBlur: 18,
      backdropSaturation: 160,
      panelBorder: 85,
      panelBorderWidth: 1.5,
      panelBorderColor: 'accent',
      panelShadow: 'glow',
      panelFill: 'accent',
      cornerRadius: 14,
      controlShape: 'round',
      barThickness: 5,
      barStyle: 'glow',
      entranceStyle: 'zoom',
    },
  },
  {
    id: 'paper',
    label: 'Paper',
    description: 'Solarized Light cards that sit on the wallpaper like sheets of paper.',
    values: {
      colorScheme: 'solarized-light',
      displayWeight: 300,
      titleStyle: 'plain',
      panelOpacity: 94,
      panelBlur: 10,
      panelBorder: 30,
      panelShadow: 'medium',
      panelFill: 'gradient',
      panelTexture: false,
      cornerRadius: 12,
      panelPadding: 16,
      panelGlow: false,
      density: 'roomy',
      iconLabelStyle: 'pill',
    },
  },
  {
    id: 'wireframe',
    label: 'Wireframe',
    description: 'Almost no fill: outlines and shadowed text over the wallpaper itself.',
    values: {
      textShadow: true,
      titleDecor: 'underline',
      panelOpacity: 8,
      panelBlur: 4,
      panelTexture: false,
      panelBorder: 70,
      panelBorderWidth: 1.5,
      panelBorderColor: 'ink',
      panelShadow: 'none',
      cornerRadius: 10,
      panelGlow: false,
    },
  },
  {
    id: 'rose',
    label: 'Rosé',
    description: 'Rosé Pine glass, pill controls, and a rose-to-iris edge.',
    values: {
      colorScheme: 'rose-pine',
      titleStyle: 'plain',
      titleDecor: 'dot',
      panelOpacity: 62,
      panelBlur: 22,
      panelBorder: 60,
      panelBorderWidth: 1.5,
      panelBorderColor: 'gradient',
      cornerRadius: 20,
      controlShape: 'pill',
      iconRadius: 16,
      barStyle: 'gradient',
      entranceStyle: 'blur',
    },
  },
  {
    id: 'dracula',
    label: 'Dracula Tabs',
    description: 'Dracula with titles in tabs, purple edges and a gradient on every meter.',
    values: {
      colorScheme: 'dracula',
      titleDecor: 'tab',
      panelOpacity: 80,
      panelBlur: 12,
      panelBorder: 40,
      panelBorderColor: 'accent',
      panelShadow: 'deep',
      cornerRadius: 12,
      controlShape: 'round',
      barStyle: 'gradient',
      entranceStyle: 'slide',
    },
  },
  {
    id: 'forest',
    label: 'Forest',
    description: 'Everforest, very round and roomy, with centred titles.',
    values: {
      colorScheme: 'everforest',
      displayWeight: 300,
      titleStyle: 'plain',
      titleAlign: 'center',
      panelOpacity: 85,
      panelBlur: 14,
      panelFill: 'gradient',
      cornerRadius: 22,
      panelPadding: 16,
      density: 'roomy',
      controlShape: 'pill',
      iconRadius: 18,
      barThickness: 6,
    },
  },

  /* ------------------------------------------------- other desktops' looks */
  {
    id: 'fluent',
    label: 'Fluent',
    description: 'Windows 11 Mica: soft acrylic, small corners and Segoe UI Variable.',
    values: {
      fontFamily: 'Segoe UI Variable Text',
      displayFont: 'Segoe UI Variable Display',
      displayWeight: 300,
      titleStyle: 'plain',
      panelOpacity: 72,
      panelBlur: 30,
      backdropSaturation: 125,
      panelBorder: 22,
      panelShadow: 'medium',
      panelTexture: false,
      cornerRadius: 8,
      controlShape: 'subtle',
      iconRadius: 6,
      entranceStyle: 'fade',
    },
  },
  {
    id: 'cupertino',
    label: 'Cupertino',
    description: 'Light frosted glass with big soft corners and a vivid, saturated blur.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#f5f5f7',
      schemeInk: '#1d1d1f',
      accentColor: '#0071e3',
      accentColor2: '#bf5af2',
      titleStyle: 'plain',
      panelOpacity: 70,
      panelBlur: 36,
      backdropSaturation: 180,
      panelBorder: 18,
      panelShadow: 'deep',
      panelTexture: false,
      cornerRadius: 22,
      panelPadding: 16,
      density: 'roomy',
      controlShape: 'pill',
      iconRadius: 18,
      entranceStyle: 'zoom',
    },
  },
  {
    id: 'material',
    label: 'Material You',
    description: 'Tonal dark cards, pill controls and a lilac wash, the Android way.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#1c1b1f',
      schemeInk: '#e6e1e5',
      accentColor: '#d0bcff',
      accentColor2: '#efb8c8',
      displayWeight: 400,
      titleStyle: 'plain',
      titleWeight: 500,
      panelOpacity: 94,
      panelBlur: 0,
      panelBorderWidth: 0,
      panelShadow: 'medium',
      panelFill: 'accent',
      panelTexture: false,
      cornerRadius: 28,
      panelPadding: 18,
      density: 'roomy',
      controlShape: 'pill',
      iconRadius: 20,
      barThickness: 6,
      entranceStyle: 'zoom',
    },
  },
  {
    id: 'adwaita',
    label: 'Adwaita',
    description: 'GNOME: solid dark cards, centred bold titles and a clear blue accent.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#242424',
      schemeInk: '#ffffff',
      accentColor: '#3584e4',
      accentColor2: '#62a0ea',
      displayWeight: 300,
      titleStyle: 'plain',
      titleAlign: 'center',
      titleWeight: 700,
      panelOpacity: 97,
      panelBlur: 0,
      panelBorder: 20,
      panelTexture: false,
      cornerRadius: 12,
      panelGlow: false,
      controlShape: 'round',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'breeze',
    label: 'Breeze',
    description: 'KDE Plasma: slate panels, crisp edges and Breeze blue.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#232629',
      schemeInk: '#fcfcfc',
      accentColor: '#3daee9',
      accentColor2: '#1d99f3',
      titleStyle: 'plain',
      panelOpacity: 88,
      panelBlur: 12,
      panelBorder: 40,
      panelShadow: 'medium',
      panelTexture: false,
      cornerRadius: 6,
      controlShape: 'subtle',
      barThickness: 5,
      entranceStyle: 'fade',
    },
  },
  {
    id: 'classic95',
    label: 'Classic 95',
    description: 'Grey bevels, navy title bars and Tahoma - the desktop from 1995.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#c0c0c0',
      schemeInk: '#000000',
      accentColor: '#000080',
      accentColor2: '#1084d0',
      fontFamily: 'Tahoma',
      displayFont: 'Tahoma',
      displayWeight: 400,
      titleStyle: 'plain',
      titleDecor: 'bar',
      titleWeight: 700,
      panelOpacity: 100,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 100,
      panelBorderWidth: 3,
      panelBorderStyle: 'outset',
      panelShadow: 'none',
      cornerRadius: 0,
      panelGlow: false,
      controlShape: 'square',
      iconRadius: 0,
      iconLabelStyle: 'plain',
      barThickness: 12,
      scrollbars: 'auto',
      entranceStyle: 'none',
    },
  },

  /* ---------------------------------------------------------- characters */
  {
    id: 'matrix',
    label: 'Matrix',
    description: 'Phosphor green on black, bracketed and glowing.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#000000',
      schemeInk: '#00ff41',
      accentColor: '#00ff41',
      accentColor2: '#008f11',
      fontFamily: 'Consolas',
      displayFont: 'Consolas',
      monoFont: 'Consolas',
      displayWeight: 400,
      textShadow: true,
      titleStyle: 'lower',
      titleDecor: 'bracket',
      panelOpacity: 85,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 50,
      panelBorderColor: 'accent',
      panelShadow: 'glow',
      cornerRadius: 0,
      panelGlow: false,
      controlShape: 'square',
      iconRadius: 0,
      barThickness: 6,
      barStyle: 'glow',
      scrollbars: 'hidden',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'amber',
    label: 'Amber CRT',
    description: 'A warm monochrome terminal, scan-line striped meters and a soft glow.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#1a0f00',
      schemeInk: '#ffb000',
      accentColor: '#ffb000',
      accentColor2: '#ff6a00',
      fontFamily: 'Lucida Console',
      displayFont: 'Lucida Console',
      monoFont: 'Lucida Console',
      displayWeight: 400,
      textShadow: true,
      titleDecor: 'underline',
      panelOpacity: 92,
      panelBlur: 0,
      panelBorder: 40,
      panelBorderColor: 'accent',
      panelShadow: 'glow',
      cornerRadius: 4,
      controlShape: 'square',
      barStyle: 'striped',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'cyberpunk',
    label: 'Cyberpunk',
    description: 'Hazard yellow and electric cyan, hard offset blocks and wide type.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#0a0a12',
      schemeInk: '#e8e8e8',
      accentColor: '#fcee0a',
      accentColor2: '#00f0ff',
      fontFamily: 'Bahnschrift',
      displayFont: 'Bahnschrift',
      letterSpacing: 4,
      titleDecor: 'bar',
      titleWeight: 800,
      panelOpacity: 90,
      panelBlur: 6,
      panelBorder: 90,
      panelBorderWidth: 2,
      panelBorderColor: 'accent',
      panelShadow: 'block',
      cornerRadius: 2,
      controlShape: 'square',
      barStyle: 'striped',
      entranceStyle: 'slide',
    },
  },
  {
    id: 'vaporwave',
    label: 'Vaporwave',
    description: 'Hot pink and cyan over deep violet, a turning gradient edge and glow.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#1b0b3a',
      schemeInk: '#ffe6ff',
      accentColor: '#ff71ce',
      accentColor2: '#01cdfe',
      displayFont: 'Trebuchet MS',
      displayWeight: 700,
      titleDecor: 'dot',
      panelOpacity: 68,
      panelBlur: 20,
      backdropSaturation: 170,
      panelBorder: 85,
      panelBorderWidth: 2,
      panelBorderColor: 'gradient',
      borderAnimation: true,
      panelShadow: 'glow',
      panelFill: 'accent',
      cornerRadius: 16,
      controlShape: 'round',
      barStyle: 'gradient',
      entranceStyle: 'zoom',
    },
  },
  {
    id: 'eink',
    label: 'E-Ink',
    description: 'Paper-white, ink-black and serif, with nothing that moves.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#f2f2ee',
      schemeInk: '#111111',
      accentColor: '#111111',
      accentColor2: '#555555',
      fontFamily: 'Georgia',
      displayFont: 'Georgia',
      displayWeight: 400,
      titleWeight: 700,
      panelOpacity: 100,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 70,
      panelBorderWidth: 1.5,
      panelBorderColor: 'ink',
      panelShadow: 'none',
      cornerRadius: 2,
      panelGlow: false,
      controlShape: 'subtle',
      iconLabelStyle: 'pill',
      barThickness: 3,
      entranceStyle: 'none',
    },
  },
  {
    id: 'oled',
    label: 'OLED Black',
    description: 'True black panels that vanish into a dark screen, hairline type.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#000000',
      schemeInk: '#f0f0f0',
      accentColor: '#ffffff',
      accentColor2: '#888888',
      displayWeight: 100,
      titleStyle: 'plain',
      titleWeight: 500,
      panelOpacity: 100,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 14,
      panelShadow: 'none',
      cornerRadius: 14,
      panelGlow: false,
      controlShape: 'round',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'contrast',
    label: 'High Contrast',
    description: 'Black, white and yellow with thick edges, for legibility first.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#000000',
      schemeInk: '#ffffff',
      accentColor: '#ffff00',
      accentColor2: '#00ffff',
      fontWeight: 600,
      displayWeight: 600,
      titleWeight: 800,
      panelOpacity: 100,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 100,
      panelBorderWidth: 2,
      panelBorderColor: 'ink',
      panelShadow: 'none',
      cornerRadius: 4,
      panelGlow: false,
      controlShape: 'subtle',
      iconLabelStyle: 'pill',
      barThickness: 8,
      entranceStyle: 'none',
    },
  },
  {
    id: 'frost',
    label: 'Frosted Glass',
    description: 'As clear as glass gets: thin fill, heavy blur, saturated colour behind.',
    values: {
      textShadow: true,
      panelOpacity: 28,
      panelBlur: 40,
      backdropSaturation: 190,
      panelBorder: 55,
      panelShadow: 'deep',
      panelFill: 'gradient',
      cornerRadius: 24,
      controlShape: 'round',
      entranceStyle: 'blur',
    },
  },
  {
    id: 'blueprint',
    label: 'Blueprint',
    description: 'White dashed lines on drafting blue, monospace and square.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#0b3d91',
      schemeInk: '#e8f1ff',
      accentColor: '#ffffff',
      accentColor2: '#9ec5ff',
      fontFamily: 'Consolas',
      displayFont: 'Consolas',
      displayWeight: 300,
      letterSpacing: 6,
      titleDecor: 'underline',
      panelOpacity: 92,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 80,
      panelBorderStyle: 'dashed',
      panelBorderColor: 'ink',
      panelShadow: 'none',
      cornerRadius: 0,
      panelGlow: false,
      controlShape: 'square',
      barStyle: 'striped',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'gameboy',
    label: 'Game Boy',
    description: 'Four shades of pea green, chunky borders and a pixel-era title bar.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#9bbc0f',
      schemeInk: '#0f380f',
      accentColor: '#306230',
      accentColor2: '#8bac0f',
      fontFamily: 'Lucida Console',
      displayFont: 'Lucida Console',
      displayWeight: 400,
      titleDecor: 'bar',
      panelOpacity: 100,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 100,
      panelBorderWidth: 3,
      panelBorderColor: 'ink',
      panelShadow: 'hard',
      cornerRadius: 4,
      panelGlow: false,
      controlShape: 'square',
      iconRadius: 0,
      barThickness: 8,
      barStyle: 'striped',
      entranceStyle: 'none',
    },
  },
  {
    id: 'concrete',
    label: 'Concrete',
    description: 'Raw grey grain, black type at its heaviest and one signal-orange accent.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#d6d3cd',
      schemeInk: '#1a1a1a',
      accentColor: '#ff3b00',
      accentColor2: '#1a1a1a',
      displayFont: 'Arial Black',
      displayWeight: 900,
      titleWeight: 900,
      panelOpacity: 100,
      panelBlur: 0,
      panelBorder: 100,
      panelBorderWidth: 2,
      panelBorderColor: 'ink',
      panelShadow: 'hard',
      cornerRadius: 0,
      panelGlow: false,
      controlShape: 'square',
      barThickness: 10,
      entranceStyle: 'drop',
    },
  },
  {
    id: 'gold',
    label: 'Black and Gold',
    description: 'Near-black, a gold double rule and widely spaced serif capitals.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#0e0e0e',
      schemeInk: '#f3e9d2',
      accentColor: '#d4af37',
      accentColor2: '#f5d77a',
      displayFont: 'Constantia',
      displayWeight: 300,
      letterSpacing: 8,
      titleWeight: 500,
      panelOpacity: 94,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 60,
      panelBorderWidth: 3,
      panelBorderStyle: 'double',
      panelBorderColor: 'accent',
      panelShadow: 'deep',
      cornerRadius: 2,
      panelGlow: false,
      controlShape: 'subtle',
      barThickness: 3,
      barStyle: 'gradient',
      entranceStyle: 'fade',
    },
  },

  /* -------------------------------------------------------------- moods */
  {
    id: 'sakura',
    label: 'Sakura',
    description: 'Blossom pink and lilac on a pale blush, soft and round.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#fff0f5',
      schemeInk: '#5a3a4a',
      accentColor: '#ff8fab',
      accentColor2: '#c9a0dc',
      displayWeight: 300,
      titleStyle: 'plain',
      titleDecor: 'dot',
      panelOpacity: 88,
      panelBlur: 18,
      panelBorder: 40,
      panelBorderWidth: 1.5,
      panelBorderColor: 'accent',
      panelFill: 'accent',
      cornerRadius: 20,
      controlShape: 'pill',
      iconLabelStyle: 'pill',
    },
  },
  {
    id: 'ocean',
    label: 'Deep Ocean',
    description: 'Bioluminescent teal and blue glowing out of the deep.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#02111b',
      schemeInk: '#cfe8f0',
      accentColor: '#2ec4b6',
      accentColor2: '#3a86ff',
      displayWeight: 200,
      panelOpacity: 70,
      panelBlur: 26,
      backdropSaturation: 150,
      panelBorder: 70,
      panelBorderWidth: 1.5,
      panelBorderColor: 'gradient',
      panelShadow: 'glow',
      panelFill: 'gradient',
      cornerRadius: 18,
      controlShape: 'round',
      barStyle: 'gradient',
    },
  },
  {
    id: 'sunset',
    label: 'Golden Hour',
    description: 'Warm amber to rose over plum, with serif numbers.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#2b1a1f',
      schemeInk: '#ffe8d6',
      accentColor: '#ff9f1c',
      accentColor2: '#ff4d6d',
      displayFont: 'Georgia',
      displayWeight: 400,
      titleStyle: 'plain',
      panelOpacity: 74,
      panelBlur: 22,
      backdropSaturation: 140,
      panelBorder: 75,
      panelBorderWidth: 2,
      panelBorderColor: 'gradient',
      panelShadow: 'deep',
      panelFill: 'accent',
      cornerRadius: 16,
      controlShape: 'round',
      barStyle: 'gradient',
    },
  },
  {
    id: 'coffee',
    label: 'Coffee House',
    description: 'Espresso, crema and a little grain; roomy and unhurried.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#2c211b',
      schemeInk: '#efe3d3',
      accentColor: '#c8a27a',
      accentColor2: '#8a5a44',
      displayFont: 'Georgia',
      displayWeight: 400,
      titleStyle: 'plain',
      panelOpacity: 90,
      panelBlur: 8,
      panelBorder: 30,
      panelShadow: 'medium',
      panelFill: 'gradient',
      cornerRadius: 10,
      density: 'roomy',
      barThickness: 5,
    },
  },
  {
    id: 'lavender',
    label: 'Lavender Fields',
    description: 'Pale lilac glass, violet tabs and pill controls.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#f3effa',
      schemeInk: '#3d3553',
      accentColor: '#9d7cd8',
      accentColor2: '#e0a3c8',
      displayWeight: 300,
      titleDecor: 'tab',
      panelOpacity: 85,
      panelBlur: 20,
      panelBorder: 30,
      panelFill: 'gradient',
      cornerRadius: 18,
      controlShape: 'pill',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'mint',
    label: 'Mint',
    description: 'Cool mint and sky on white, light and quick.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#eefaf5',
      schemeInk: '#1f3a33',
      accentColor: '#2bb673',
      accentColor2: '#5ec8e5',
      displayWeight: 300,
      titleStyle: 'plain',
      panelOpacity: 90,
      panelBlur: 12,
      panelBorder: 25,
      cornerRadius: 14,
      controlShape: 'round',
      barStyle: 'gradient',
    },
  },
  {
    id: 'forest-night',
    label: 'Midnight Forest',
    description: 'Pine-dark glass with moss and ember accents, and a little grain.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#0f1a14',
      schemeInk: '#d8e5d0',
      accentColor: '#7fb069',
      accentColor2: '#e6aa68',
      displayWeight: 300,
      panelOpacity: 78,
      panelBlur: 24,
      panelBorder: 30,
      panelShadow: 'deep',
      panelFill: 'gradient',
      cornerRadius: 16,
      controlShape: 'round',
    },
  },
  {
    id: 'nordic-light',
    label: 'Nordic Light',
    description: 'Snowy Nord greys, frost-blue accents and a lot of air.',
    values: {
      followTheme: false,
      colorScheme: 'custom',
      schemeGround: '#eceff4',
      schemeInk: '#2e3440',
      accentColor: '#5e81ac',
      accentColor2: '#88c0d0',
      displayWeight: 200,
      titleStyle: 'plain',
      titleWeight: 500,
      panelOpacity: 92,
      panelBlur: 10,
      panelTexture: false,
      panelBorder: 20,
      cornerRadius: 10,
      panelPadding: 16,
      panelGlow: false,
      density: 'roomy',
      controlShape: 'subtle',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'ink-wash',
    label: 'Ink Wash',
    description: 'Kanagawa colours, serif numbers and quiet paper grain.',
    values: {
      colorScheme: 'kanagawa',
      displayFont: 'Georgia',
      displayWeight: 300,
      letterSpacing: 2,
      titleStyle: 'plain',
      titleWeight: 400,
      panelOpacity: 88,
      panelBlur: 14,
      panelBorder: 20,
      cornerRadius: 4,
      controlShape: 'subtle',
      entranceStyle: 'fade',
    },
  },

  /* ------------------------------------------------------ scheme classics */
  {
    id: 'solar-terminal',
    label: 'Solarized Terminal',
    description: 'Solarized Dark in a tiling-WM frame: monospace, square, bracketed.',
    values: {
      colorScheme: 'solarized-dark',
      fontFamily: 'Consolas',
      displayFont: 'Consolas',
      monoFont: 'Consolas',
      displayWeight: 400,
      titleStyle: 'lower',
      titleDecor: 'bracket',
      panelOpacity: 95,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 40,
      panelBorderColor: 'ink',
      panelShadow: 'none',
      cornerRadius: 0,
      panelGlow: false,
      controlShape: 'square',
      barThickness: 6,
      barStyle: 'striped',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'github',
    label: 'GitHub',
    description: 'GitHub Dark, flat and tidy, with small corners.',
    values: {
      colorScheme: 'github-dark',
      displayWeight: 300,
      titleStyle: 'plain',
      panelOpacity: 96,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 40,
      panelShadow: 'none',
      cornerRadius: 6,
      panelGlow: false,
      controlShape: 'subtle',
      entranceStyle: 'fade',
    },
  },
  {
    id: 'carbon',
    label: 'Carbon',
    description: 'Oxocarbon with no edges and no shadows, spaced capitals, square everything.',
    values: {
      colorScheme: 'oxocarbon',
      displayWeight: 300,
      letterSpacing: 4,
      titleWeight: 400,
      panelOpacity: 97,
      panelBlur: 0,
      panelTexture: false,
      panelBorderWidth: 0,
      panelShadow: 'none',
      cornerRadius: 0,
      panelGlow: false,
      controlShape: 'square',
      barThickness: 3,
      entranceStyle: 'fade',
    },
  },
  {
    id: 'moonlight-glass',
    label: 'Moonlight Glass',
    description: 'Moonlight blues through clear glass, with a gradient edge.',
    values: {
      colorScheme: 'moonlight',
      titleDecor: 'dot',
      panelOpacity: 58,
      panelBlur: 30,
      backdropSaturation: 150,
      panelBorder: 70,
      panelBorderWidth: 1.5,
      panelBorderColor: 'gradient',
      panelShadow: 'deep',
      cornerRadius: 18,
      controlShape: 'round',
      entranceStyle: 'blur',
    },
  },
  {
    id: 'poimandres',
    label: 'Poimandres',
    description: 'Muted slate with minty glowing accents.',
    values: {
      colorScheme: 'poimandres',
      titleStyle: 'plain',
      panelOpacity: 82,
      panelBlur: 16,
      panelBorder: 30,
      panelBorderColor: 'accent',
      panelShadow: 'glow',
      cornerRadius: 12,
      controlShape: 'round',
      barStyle: 'gradient',
      entranceStyle: 'zoom',
    },
  },
  {
    id: 'ayu',
    label: 'Ayu Mirage',
    description: 'Ayu Mirage with underlined titles and quick sliding entrances.',
    values: {
      colorScheme: 'ayu-mirage',
      titleStyle: 'plain',
      titleDecor: 'underline',
      panelOpacity: 90,
      panelBlur: 8,
      panelBorder: 25,
      panelShadow: 'medium',
      cornerRadius: 8,
      entranceStyle: 'slide',
    },
  },
  {
    id: 'night-owl',
    label: 'Night Owl',
    description: 'Midnight-blue glass with a periwinkle wash and accent edges.',
    values: {
      colorScheme: 'night-owl',
      displayWeight: 200,
      titleDecor: 'dot',
      panelOpacity: 80,
      panelBlur: 20,
      panelBorder: 35,
      panelBorderColor: 'accent',
      panelShadow: 'deep',
      panelFill: 'accent',
      cornerRadius: 14,
      controlShape: 'round',
    },
  },
  {
    id: 'cobalt',
    label: 'Cobalt',
    description: 'Cobalt2: bold yellow edges and blocks on deep blue, titles in tabs.',
    values: {
      colorScheme: 'cobalt2',
      titleDecor: 'tab',
      titleWeight: 700,
      panelOpacity: 94,
      panelBlur: 0,
      panelTexture: false,
      panelBorder: 70,
      panelBorderWidth: 2,
      panelBorderColor: 'accent',
      panelShadow: 'block',
      cornerRadius: 6,
      controlShape: 'subtle',
      barThickness: 6,
      entranceStyle: 'drop',
    },
  },
  {
    id: 'macchiato',
    label: 'Catppuccin Soft',
    description: 'Catppuccin Macchiato, round and gentle, with gradient meters.',
    values: {
      colorScheme: 'catppuccin-macchiato',
      titleStyle: 'plain',
      titleDecor: 'dot',
      panelOpacity: 75,
      panelBlur: 24,
      panelBorder: 25,
      cornerRadius: 18,
      controlShape: 'pill',
      iconRadius: 16,
      barStyle: 'gradient',
      entranceStyle: 'zoom',
    },
  },
  {
    id: 'gruvbox-soft',
    label: 'Gruvbox Soft',
    description: 'Gruvbox Material, warm and matte, with rounded cards.',
    values: {
      colorScheme: 'gruvbox-material',
      displayWeight: 300,
      titleStyle: 'plain',
      panelOpacity: 92,
      panelBlur: 6,
      panelBorder: 25,
      panelShadow: 'medium',
      panelFill: 'gradient',
      cornerRadius: 12,
      density: 'roomy',
      controlShape: 'round',
    },
  },
  {
    id: 'everforest-day',
    label: 'Everforest Day',
    description: 'Everforest Light: parchment, sage and moss, calm and bright.',
    values: {
      colorScheme: 'everforest-light',
      displayWeight: 300,
      titleStyle: 'plain',
      panelOpacity: 93,
      panelBlur: 10,
      panelBorder: 25,
      panelShadow: 'soft',
      cornerRadius: 14,
      controlShape: 'round',
      iconLabelStyle: 'pill',
    },
  },
];

export function lookById(id: string): Look | undefined {
  return LOOKS.find((look) => look.id === id);
}

/** Just the appearance part of a config. */
export function pickAppearance(cfg: Appearance): Appearance {
  return Object.fromEntries(APPEARANCE_KEYS.map((key) => [key, cfg[key]])) as Appearance;
}

/** A look spelled out in full: its own values over the defaults. */
export function resolveLook(look: Look, defaults: Appearance): Appearance {
  return { ...pickAppearance(defaults), ...look.values };
}

/** The look the settings currently match exactly, if any - for a tick in a menu. */
export function currentLook(cfg: Appearance, defaults: Appearance): string | null {
  for (const look of LOOKS) {
    const want = resolveLook(look, defaults);
    if (APPEARANCE_KEYS.every((key) => Object.is(cfg[key], want[key]))) return look.id;
  }
  return null;
}

/** The marker an exported appearance carries, so a pasted recipe is recognised as one. */
const MARKER = '$desktopAppearance';

/**
 * The current appearance as text someone else can paste into their own surface.
 *
 * `shell` is the Desktop Surface theme's settings as stored, so an exported
 * rice carries the dock and the start menu as well as the desktop.
 */
export function exportAppearance(cfg: Pick<DesktopConfig, ShareKey>, shell: Record<string, string> = {}): string {
  const out: Record<string, unknown> = { [MARKER]: 1 };
  for (const key of [...APPEARANCE_KEYS, ...SHARED_EXTRA_KEYS]) out[key] = cfg[key];
  if (Object.keys(shell).length) out.shell = shell;
  return JSON.stringify(out, null, 2);
}

export type ParsedAppearance =
  | {
      ok: true;
      values: Partial<Pick<DesktopConfig, ShareKey>>;
      /** Theme settings as strings; pass them through `shareableShell` before writing. */
      shell: Record<string, string>;
      skipped: string[];
    }
  | { ok: false; error: string };

/**
 * Reads a pasted appearance back.
 *
 * Only keys this build knows are taken, and only when the value has the type
 * the default has - a recipe from a newer build, or a hand-edited one with a
 * typo, applies what it can and says what it left out rather than writing a
 * string into a slider.
 */
export function parseAppearance(text: string, defaults: Pick<DesktopConfig, ShareKey>): ParsedAppearance {
  let data: unknown;
  try {
    data = JSON.parse(text);
  } catch {
    return { ok: false, error: 'That is not valid JSON.' };
  }
  if (!data || typeof data !== 'object' || Array.isArray(data)) {
    return { ok: false, error: 'Expected an object of settings.' };
  }

  const known = new Set<string>([...APPEARANCE_KEYS, ...SHARED_EXTRA_KEYS]);
  const values: Record<string, unknown> = {};
  const shell: Record<string, string> = {};
  const skipped: string[] = [];
  for (const [key, value] of Object.entries(data)) {
    if (key === MARKER) continue;
    // The theme's settings, taken as strings; the caller keeps only real knobs.
    if (key === 'shell' && value && typeof value === 'object' && !Array.isArray(value)) {
      for (const [name, stored] of Object.entries(value)) {
        if (name.startsWith('--rs-') && typeof stored === 'string') shell[name] = stored;
        else skipped.push(`shell.${name}`);
      }
      continue;
    }
    if (!known.has(key)) {
      skipped.push(key);
      continue;
    }
    if (typeof value !== typeof defaults[key as ShareKey]) {
      skipped.push(key);
      continue;
    }
    values[key] = value;
  }
  if (!Object.keys(values).length && !Object.keys(shell).length) {
    return { ok: false, error: 'No appearance settings found in it.' };
  }
  return { ok: true, values: values as Partial<Pick<DesktopConfig, ShareKey>>, shell, skipped };
}
